[package]
name = "forthdb-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
default-run = "forthdb-bench"

[dependencies]
forthdb-core = { path = "../forthdb-core" }
forthdb-world = { path = "../forthdb-world" }
serde.workspace = true
serde_json.workspace = true
