[package]
name = "forthdb-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/wrapper.rs"

[features]
fault-injection = []

[dependencies]
forthdb-core = { path = "../forthdb-core" }
memmap2 = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7"
libc = "0.2"
